export const ADD_POSTS_TO_BEGINNING = 'ADD_POSTS_TO_BEGINNING';
export const ADD_POSTS_TO_END = 'ADD_POSTS_TO_END';
export const FETCH_NEWS = 'FETCH_NEWS';
export const CHANGE_NEXT_PAGE = 'CHANGE_NEXT_PAGE';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const DESELECT_CATEGORY = 'DESELECT_CATEGORY';

export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';